name: demo action121
on:
  workflow_dispatch:
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: run a sample
        run: echo "Hello, world!"

      - uses: actions/upload-artifact@v4
        name: upload artifact
        with:
          name: build-artifact
          path: ${{ github.workspace }}

      # Assuming you want to deploy here, add your deploy logic:
      - name: deploy
        run: echo "Deploying the application..."  # replace with actual deployment command

      - uses: actions/download-artifact@v2
        name: download artifact
        with:
          name: build-artifact
          path: ./downloaded-artifacts
