name: demo action121
on:
  push:
    branches: master
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: run a sample
        run: echo "Hello, world!"

      - uses: actions/upload-artifact@v4
      - name: upload artifect
        with:
          name: build-artifact
          path: ${{github.workpace}}
  
