name: demo action
on:
  push:
    branches: main
jobs:
  build:    
    runs-on: ubuntu-lates
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: run a sample
      - run: echo "Hello, world!"
