name: demo action121
on:
  workflow_dispatch:
jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: run a sample
        run: echo "Hello, world!"

      - uses: actions/upload-artifact@v4
        name: upload artifact
        with:
          name: build-artifact
          path: ${{ github.workspace }}
